openapi: "3.0.0"
info:
  title: HockeyTrackerApi
  version: 1.0.0
  description: API for hockey tracker app
paths:
  /players:
    get:
      operationId: getPlayers
      tags: [getPlayers]
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlayerListResponse"
          description: 'OK'
    post:
      operationId: createPlayer
      tags: [CreatePlayer]
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Player"
      responses:
        '202':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Player"
          description: 'OK'
  /players/{guid}:
    get:
      operationId: getPlayerByGuid
      tags: [getPlayer]
      parameters:
        - in: path
          name: guid
          required: true
          schema:
            type: string
          description: The player ID.
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Player"
          description: 'OK'
    put:
      operationId: updatePlayerByGuid
      tags: [ updatePlayer ]
      parameters:
        - in: path
          name: guid
          required: true
          schema:
            type: string
          description: The player guid.
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Player"
          description: 'OK'
    delete:
      operationId: deletePlayerByGuid
      tags: [ deletePlayer ]
      parameters:
        - in: path
          name: guid
          required: true
          schema:
            type: string
          description: The player guid.
      responses:
        '200':
          description: 'OK'
components:
  schemas:
    League:
      type: object
      required:
        - leagueName
      properties:
        leagueName:
          type: string
        publicId:
          type: string
        teams:
          type: array
          uniqueItems: true
          items:
            $ref: "#/components/schemas/TeamData"
        players:
          type: array
          uniqueItems: true
          items:
            $ref: "#/components/schemas/PlayerData"
    LeagueData:
      type: object
      required:
        - leagueName
        - publicId
      properties:
        leagueName:
          type: string
        publicId:
          type: string
    LeagueListResponse:
      type: object
      required:
        - leagueList
      properties:
        leagueList:
          type: array
          uniqueItems: true
          items:
            $ref: "#/components/schemas/League"
    LeagueResponse:
      type: object
      required:
        - league
      properties:
        league:
          $ref: "#/components/schemas/League"
    Player:
      type: object
      required:
        - playerName
      properties:
        playerName:
          type: string
        dob:
          type: string
        position:
          type: string
        publicId:
          type: string
        teams:
          type: array
          uniqueItems: true
          items:
            $ref: "#/components/schemas/TeamData"
        leagues:
          type: array
          uniqueItems: true
          items:
            $ref: "#/components/schemas/LeagueData"
        image:
          type: string
    PlayerData:
      type: object
      required:
        - playerName
      properties:
        playerName:
          type: string
        dob:
          type: string
        position:
          type: string
        publicId:
          type: string
        image:
          type: string
    PlayerListResponse:
      type: object
      required:
        - playerList
      properties:
        playerList:
          type: array
          uniqueItems: true
          items:
            $ref: "#/components/schemas/Player"
    PlayerResponse:
      type: object
      required:
        - player
      properties:
        player:
          $ref: "#/components/schemas/Player"
    PlayerCoreDetailUpdate:
      type: object
      required:
        - updatedPlayerData
      properties:
        updatedPlayerData:
          $ref: "#/components/schemas/PlayerData"
    PlayerLeaguesUpdate:
      type: object
      required:
        - updatedLeagues
      properties:
        updatedLeagues:
          type: array
          items:
            $ref: "#/components/schemas/LeagueData"
    PlayerTeamsUpdate:
      type: object
      required:
        - updatedTeams
      properties:
        updatedTeams:
          type: array
          items:
            $ref: "#/components/schemas/TeamData"
    Team:
      type: object
      required:
        - teamName
      properties:
        teamName:
          type: string
        publicId:
          type: string
        players:
          type: object
          uniqueItems: true
          items:
            $ref: "#/components/schemas/PlayerData"
        leagues:
          type: array
          uniqueItems: true
          items:
            $ref: "#/components/schemas/LeagueData"
    TeamData:
      type: object
      required:
        - teamName
        - publicId
      properties:
        teamName:
          type: string
        publicId:
          type: string
    TeamListResponse:
      type: object
      required:
        - teamList
      properties:
        teamList:
          type: array
          uniqueItems: true
          items:
            $ref: "#/components/schemas/Team"
    TeamResponse:
      type: object
      required:
        - team
      properties:
        team:
          $ref: "#/components/schemas/Team"
